newfies/appointment/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2013 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import patterns

urlpatterns = patterns('appointment.views',

    (r'^module/calendar_user/$', 'calendar_user_list'),
    (r'^module/calendar_user/add/$', 'calendar_user_add'),
    (r'^module/calendar_user/del/(.+)/$', 'calendar_user_del'),
    (r'^module/calendar_user/password/(.+)/$', 'calendar_user_change_password'),
    (r'^module/calendar_user/(.+)/$', 'calendar_user_change'),

    # Calendars urls
    (r'^module/calendar/$', 'calendar_list'),
    (r'^module/calendar/add/$', 'calendar_add'),
    (r'^module/calendar/del/(.+)/$', 'calendar_del'),
    (r'^module/calendar/(.+)/$', 'calendar_change'),

    # Calendar settings urls
    (r'^module/calendar_setting/$', 'calendar_setting_list'),
    (r'^module/calendar_setting/add/$', 'calendar_setting_add'),
    (r'^module/calendar_setting/del/(.+)/$', 'calendar_setting_del'),
    (r'^module/calendar_setting/(.+)/$', 'calendar_setting_change'),

    # Events urls
    (r'^module/event/$', 'event_list'),
    (r'^module/event/add/$', 'event_add'),
    (r'^module/event/del/(.+)/$', 'event_del'),
    (r'^module/event/(.+)/$', 'event_change'),

    # Alarms urls
    (r'^module/alarm/$', 'alarm_list'),
    (r'^module/alarm/add/$', 'alarm_add'),
    (r'^module/alarm/del/(.+)/$', 'alarm_del'),
    (r'^module/alarm/(.+)/$', 'alarm_change'),
)

newfies/newfies_dialer/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2013 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns, url
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
from agent.urls import urlpatterns as urlpatterns_agent
from callcenter.urls import urlpatterns as urlpatterns_callcenter
from sms_module.urls import urlpatterns as urlpatterns_sms_module
from dajaxice.core import dajaxice_autodiscover
from django.contrib import admin
import os


admin.autodiscover()
dajaxice_autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
    (r'^logout/$', 'frontend.views.logout_view'),
    (r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    #(r'^sentry/', include('sentry.web.urls')),
    (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )


urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
urlpatterns += urlpatterns_agent
urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_sms_module

urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

newfies/urls.py
#
# Newfies-Dialer License
# http://www.newfies-dialer.org
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (C) 2011-2013 Star2Billing S.L.
#
# The Initial Developer of the Original Code is
# Arezqui Belaid <info@star2billing.com>
#
from django.conf.urls import handler404, handler500, \
    include, patterns
from django.conf import settings
from apirest.urls import urlpatterns as urlpatterns_apirest
from agent.api_urls import urlpatterns as urlpatterns_agent_apirest
from appointment.urls import urlpatterns as urlpatterns_appointment
from frontend.urls import urlpatterns as urlpatterns_frontend
from dialer_contact.urls import urlpatterns as urlpatterns_dialer_contact
from dialer_campaign.urls import urlpatterns as urlpatterns_dialer_campaign
from dialer_cdr.urls import urlpatterns as urlpatterns_dialer_cdr
from dnc.urls import urlpatterns as urlpatterns_dnc
from user_profile.urls import urlpatterns as urlpatterns_user_profile
from survey.urls import urlpatterns as urlpatterns_survey
from dialer_audio.urls import urlpatterns as urlpatterns_dialer_audio
from frontend_notification.urls import urlpatterns as urlpatterns_frontend_notification
from agent.urls import urlpatterns as urlpatterns_agent
from callcenter.urls import urlpatterns as urlpatterns_callcenter
from sms_module.urls import urlpatterns as urlpatterns_sms_module
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover
import os


dajaxice_autodiscover()

try:
    admin.autodiscover()
except admin.sites.AlreadyRegistered:
    # nose imports the admin.py files during tests, so
    # the models have already been registered.
    pass

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('dialer_campaign',
                 'user_profile',
                 'survey',
                 'audiofield'),
}

urlpatterns = patterns('',
    (r'^logout/$', 'frontend.views.logout_view'),
    (r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    #(r'^sentry/', include('sentry.web.urls')),
    (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)

urlpatterns += urlpatterns_apirest
urlpatterns += urlpatterns_agent_apirest
urlpatterns += urlpatterns_frontend
urlpatterns += urlpatterns_dialer_contact
urlpatterns += urlpatterns_dialer_campaign
urlpatterns += urlpatterns_dialer_cdr
urlpatterns += urlpatterns_dnc
urlpatterns += urlpatterns_user_profile
urlpatterns += urlpatterns_survey
urlpatterns += urlpatterns_dialer_audio
urlpatterns += urlpatterns_frontend_notification
urlpatterns += urlpatterns_agent
urlpatterns += urlpatterns_callcenter
urlpatterns += urlpatterns_appointment
urlpatterns += urlpatterns_sms_module

urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip(os.sep),
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)


handler404 = 'urls.custom_404_view'
handler500 = 'urls.custom_500_view'


def custom_404_view(request, template_name='404.html'):
    """404 error handler which includes ``request`` in the context.

    Templates: `404.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('404.html')  # Need to create a 404.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))


def custom_500_view(request, template_name='500.html'):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # Need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

newfies/appointment/models/calendars.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.utils import timezone
from appointment.models.users import CalendarUser
import datetime
import pytz


class Calendar(models.Model):
    """
    This is for grouping events so that batch relations can be made to all
    events.  An example would be a project calendar.

    name: the name of the calendar
    events: all the events contained within the calendar.
    >>> calendar = Calendar(name = 'Test Calendar')
    >>> calendar.save()
    """
    name = models.CharField(verbose_name=_('name'), max_length=200)
    user = models.ForeignKey(CalendarUser, blank=True, null=True,
                             verbose_name=_("calendar user"),
                             help_text=_("select user"),
                             related_name="calendar user")
    max_concurrent = models.IntegerField(null=True, blank=True, default=0,
                                         help_text=_("Max concurrent is not implemented"))
    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('date'))

    class Meta:
        permissions = (
            ("view_calendar ", _('Can see Calendar list')),
        )
        verbose_name = _('calendar')
        verbose_name_plural = _('calendars')
        app_label = "appointment"

    def __unicode__(self):
        return self.name

    @property
    def events(self):
        return self.event_set

    def get_recent(self, amount=5, in_datetime=datetime.datetime.now, tzinfo=pytz.utc):
        """
        This shortcut function allows you to get events that have started recently.

        amount is the amount of events you want in the queryset. The default is 5.

        in_datetime is the datetime you want to check against.  It defaults to datetime.datetime.now
        """
        return self.events.order_by('-start').filter(start__lt=timezone.now())[:amount]

    def get_absolute_url(self):
        return reverse('calendar_home', kwargs={'calendar_slug': self.slug})

    def add_event_url(self):
        return reverse('s_create_event_in_calendar', args=[self.slug])

newfies/apt_reminder/models/alarms.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import force_unicode
from apt_reminder.constants import ALARM_METHOD, ALARM_STATUS, ALARM_RESULT
from apt_reminder.models.events import Event
from survey.modles import Survey
from dialer_cdr.models import CallRequest
from mail.models import Mailtemplate


class SMSTemplate(models.Model):
    """
    This table store the SMS Template
    """
    label = models.CharField(max_length=75,
                    help_text='SMS template name')
    template_key = models.CharField(max_length=30, unique=True,
                    help_text='Unique name used to pick some template for recurring action, such as activation or warning')
    sender_phonenumber = models.EmailField(max_length=75, help_text='Sender Email')
    sms_text = models.TextField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('SMS template')
        verbose_name_plural = _('SMS templates')

    def __unicode__(self):
        return force_unicode(self.template_key)


class Alarm(models.Model):
    '''
    This is for Alarms / Reminders on events models.
    '''
    #TODO: maybe integer ?
    daily_start = models.DateTimeField(verbose_name=_('daily start'))
    daily_stop = models.DateTimeField(verbose_name=_('daily stop'))
    advance_notice = models.IntegerField(null=True, blank=True, default=0,
                                         verbose_name=_('advance notice'))
    retry_count = models.IntegerField(null=True, blank=True, default=0,
                                      verbose_name=_('retry count'))
    retry_delay = models.IntegerField(null=True, blank=True, default=0,
                                      verbose_name=_('retry delay'))
    sent_count = models.IntegerField(null=True, blank=True, default=0,
                                     verbose_name=_('sent count'))
    method = models.IntegerField(choices=list(ALARM_METHOD),
                                 default=ALARM_METHOD.CALL,
                                 verbose_name=_("method"), blank=True, null=True)

    # TODO: Add missing fields

    survey = models.ForeignKey(Survey, verbose_name=_("survey"),
                               related_name="survey")
    mail_template = models.ForeignKey(Mailtemplate, verbose_name=_("mail template"),
                                     related_name="mail template")
    sms_template = models.ForeignKey(SMSTemplate, verbose_name=_("sms template"),
                                     related_name="sms template")
    event = models.ForeignKey(Event, verbose_name=_("event"),
                              related_name="event")

    date_start_notice = models.DateTimeField(verbose_name=_('starting date'))
    status = models.IntegerField(choices=list(ALARM_STATUS),
                                 default=ALARM_STATUS.PENDING,
                                 verbose_name=_("status"), blank=True, null=True)
    result = models.IntegerField(choices=list(ALARM_RESULT),
                                 verbose_name=_("method"), blank=True, null=True)
    url_cancel = models.CharField(max_length=250, blank=True, null=True,
                                verbose_name=_("URL cancel"))
    phonenumber_sms_cancel = models.CharField(max_length=50, blank=True, null=True,
                                verbose_name=_("phonenumber SMS cancel"))
    url_confirm = models.CharField(max_length=250, blank=True, null=True,
                                verbose_name=_("URL confirm"))
    phonenumber_transfer = models.CharField(max_length=50, blank=True, null=True,
                                verbose_name=_("phonenumber transfer"))

    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('date'))

    class Meta:
        verbose_name = _('alarm')
        verbose_name_plural = _('alarms')

    def __unicode__(self):
        return self.id


class AlarmRequest(models.Model):
    '''
    AlarmRequest : request for Alarms
    '''
    alarm = models.ForeignKey(Alarm, blank=True, null=True, verbose_name=_("alarm"),
                             help_text=_("select alarm"),
                             related_name="request_alarm")
    date = models.DateTimeField(verbose_name=_('date'))

    #TODO: method should be a CHOICE
    status = models.IntegerField(null=True, blank=True, default=0)
    callstatus = models.IntegerField(null=True, blank=True, default=0)

    calltime = models.DateTimeField(verbose_name=_('call time'))
    duration = models.IntegerField(null=True, blank=True, default=0)

    callrequest = models.ForeignKey(CallRequest, blank=True, null=True,
                                    verbose_name=_("Call Request"),
                                    help_text=_("select call request"),
                                    related_name="callrequest_alarm")

    created_date = models.DateTimeField(auto_now_add=True,
                                        verbose_name=_('date'))

    class Meta:
        verbose_name = _('alarm request')
        verbose_name_plural = _('alarm requests')

    def __unicode__(self):
        return self.id

newfies/templates/frontend/appointment/alarm/change.html
{% extends "frontend/master.html" %}
{% load i18n common_tags %}

{% block extra_files %}
    {{ form.media }}
{% endblock %}

{% block content_header %}
    <h1>
        {% if action == 'update' %}
            {% trans "update"|title %}
        {% else %}
            {% trans "add"|title %}
        {% endif %}
        {% trans "alarm"|title %}
        <small></small>
    </h1>
{% endblock %}

{% block content %}
<ul class="nav nav-tabs">
    <li class="active"><a href="#tabs-1" data-toggle="tab">{% trans "general settings"|title %}</a></li>
    <li class="{% if action == 'tabs-2' %}active{% endif %}"><a href="#tabs-2" data-toggle="tab">{% trans "alarm settings"|title %}</a></li>
    <li class="{% if action == 'tabs-3' %}active{% endif %}"><a href="#tabs-3" data-toggle="tab">{% trans "result settings"|title %}</a></li>
</ul>
<form class="well" role="form" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
    <div class="tab-content">
        <div id="tabs-1" class="tab-pane active">
            <div class="row">
                {% get_fieldset alarm_phonenumber,alarm_email,event,method,survey,mail_template,sms_template,date_start_notice as general_fields from form %}
                {% for field in general_fields.hidden_fields %}
                    {{ field }}
                {% endfor %}
                {% for field in general_fields.visible_fields %}
                    <div class="col-md-6">
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="col-xs-8">
                            <label class="control-label" for="{{ field.auto_id }}">{{ field.label|wordcap }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="help-inline">
                                    {{ field.errors|removetags:"ul li"|safe }}
                                </span>
                            {% endif %}
                            <span class="help-block">
                                {{ field.help_text|capfirst }}
                            </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div id="tabs-2" class="tab-pane {% if action == 'tabs-2' %}active{% endif %}">

            <div class="row">
                {% get_fieldset daily_start,daily_stop,advance_notice,maxretry,retry_delay as alarm_fields from form %}
                {% for field in alarm_fields.hidden_fields %}
                    {{ field }}
                {% endfor %}
                {% for field in alarm_fields.visible_fields %}
                    <div class="col-md-6">
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="col-xs-8">
                            <label class="control-label" for="{{ field.auto_id }}">{{ field.label|wordcap }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="help-inline">
                                    {{ field.errors|removetags:"ul li"|safe }}
                                </span>
                            {% endif %}
                            <span class="help-block">
                                {{ field.help_text|capfirst }}
                            </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div id="tabs-3" class="tab-pane {% if action == 'tabs-3' %}active{% endif %}">
            <div class="row">
                {% get_fieldset result,url_cancel,phonenumber_sms_failure,url_confirm,phonenumber_transfer as result_fields from form %}
                {% for field in result_fields.hidden_fields %}
                    {{ field }}
                {% endfor %}
                {% for field in result_fields.visible_fields %}
                    <div class="col-md-6">
                        <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="col-xs-8">
                            <label class="control-label" for="{{ field.auto_id }}">{{ field.label|wordcap }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <span class="help-inline">
                                    {{ field.errors|removetags:"ul li"|safe }}
                                </span>
                            {% endif %}
                            <span class="help-block">
                                {{ field.help_text|capfirst }}
                            </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include "frontend/common_submit_buttons.html" %}
</form>

{% endblock %}

newfies/templates/frontend/appointment/alarm/list.html
{% extends "frontend/master.html" %}
{% load i18n pagination_tags common_tags appointment_tags %}

{% block extra_files %}
    {% include "frontend/custom_jquery_select_all.html" %}
{% endblock %}

{% block content_header %}
    <h1>{% trans "alarms"|title %} <small>{% trans "list, add and edit alarm"|capfirst %}</small></h1>
{% endblock %}

{% block content %}

<script type="text/javascript">
    function add_button()
    {
        window.location = 'add/';
    }

    function delete_button()
    {
        $('#ListForm').submit();
    }
</script>

<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            {% trans "action"|capfirst %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                {% if perms.appointment.delete_alarm %}
                    <li><a href="#" onclick="delete_button()">{% trans "delete selected"|title %}</a></li>
                {% endif %}
            </ul>
        </div>

        {% if perms.appointment.add_alarm %}
            <button type="button" class="btn btn-info" onclick="add_button()">
                <i class="fa fa-plus"></i> {% trans "add"|title %}
            </button>
        {% endif %}
    </div>
</div>

<br/>

<div class="row">
    <div class="col-md-12">

        <form method="POST" action="del/0/" enctype="multipart/form-data" id="ListForm">{% csrf_token %}
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th><input type="checkbox" onclick="toggleChecked(this.checked)"></th>
                        <th>{% sort_link ALARM_COLUMN_NAME.date_start_notice|title col_name_with_order.date_start_notice %}</th>
                        <th>{% sort_link ALARM_COLUMN_NAME.alarm_phonenumber|title col_name_with_order.alarm_phonenumber %}</th>
                        {# <th>{% sort_link ALARM_COLUMN_NAME.alarm_email|capfirst col_name_with_order.alarm_email %}</th> #}
                        {# <th>{% sort_link ALARM_COLUMN_NAME.daily_start|title col_name_with_order.daily_start %}</th> #}
                        {# <th>{% sort_link ALARM_COLUMN_NAME.daily_stop|title col_name_with_order.daily_stop %}</th> #}
                        <th>{% sort_link ALARM_COLUMN_NAME.method|capfirst col_name_with_order.method %}</th>
                        <th>{% sort_link ALARM_COLUMN_NAME.survey|capfirst col_name_with_order.survey %}</th>
                        <th>{% sort_link ALARM_COLUMN_NAME.event|capfirst col_name_with_order.event %}</th>
                        <th>{% sort_link ALARM_COLUMN_NAME.status|capfirst col_name_with_order.status %}</th>
                        <th>{% trans 'action'|capfirst %}</th>
                    </tr>
                    </thead>
                    {% if alarm_list %}
                        {% autopaginate alarm_list PAGE_SIZE %}
                        {% for row in alarm_list %}
                            <tr>
                                <td><input type="checkbox" name="select" class="checkbox" value="{{ row.id }}" /></td>
                                <td>{{ row.date_start_notice }}</td>
                                <td>{{ row.alarm_phonenumber }}</td>
                                {# <td>{{ row.alarm_email }}</td> #}
                                {# <td>{{ row.daily_start }}</td> #}
                                {# <td>{{ row.daily_stop }}</td> #}
                                <td>{{ row.method|alarm_method }}</td>
                                <td>{{ row.survey }}</td>
                                <td>{{ row.event }}</td>
                                <td>{{ row.status|alarm_status }}</td>
                                <td>
                                    {% if perms.appointment.change_alarm %}
                                        <a href="{{ row.id }}/" title="{% trans 'update alarm'|title %}"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if perms.appointment.delete_alarm %}
                                        <a id="id_delete_confirm" href="del/{{ row.id }}/" title="{% trans 'delete alarm'|title %}"><i class="fa fa-trash-o"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="11" align="center">
                                {% trans "no records found"|title %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
            <div class="text-right">
                {% trans "total"|title %} : {{ total_alarm }}
            </div>
            {% if alarm_list %}
                {% paginate %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}